volumes:
  tfidf_db:

services:

  db:
    image: postgres:17.5
    container_name: tfidf_db
    restart: always
    env_file: .env
    volumes:
      - tfidf_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: khamtsev/tfidf_backend
    container_name: tfidf_backend
    restart: always
    env_file: .env
    ports:
      - 80:8000
    depends_on:
      - db
