volumes:
  tfidf_db:

services:

  db:
    image: postgres:17.5
    env_file: .env
    volumes:
      - tfidf_db:/var/lib/postgresql/data
  
  backend:
    build: .
    env_file: .env
    ports:
      - 80:8000
    depends_on:
      - db
