# Generated by Django 5.2 on 2025-06-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_requests', models.PositiveIntegerField(default=0)),
                ('latest_statistics_processed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('min_time_processed', models.FloatField(default=0.0)),
                ('total_time_processed', models.FloatField(default=0.0)),
                ('avg_time_processed', models.FloatField(default=0.0)),
                ('max_time_processed', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_requests', models.PositiveIntegerField(default=0)),
                ('latest_statistics_processed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('min_time_processed', models.FloatField(default=0.0)),
                ('total_time_processed', models.FloatField(default=0.0)),
                ('avg_time_processed', models.FloatField(default=0.0)),
                ('max_time_processed', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
