# Generated by Django 5.2 on 2025-06-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='collections',
        ),
        migrations.CreateModel(
            name='CollectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collections')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
            options={
                'unique_together': {('collection', 'document')},
            },
        ),
        migrations.AddField(
            model_name='collections',
            name='documents',
            field=models.ManyToManyField(related_name='collections', through='core.CollectionDocument', to='core.document'),
        ),
    ]
